version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    expose:
      - "3306"

  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - "80:80"
    command: >
        bash -c "python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:80"
                
# this deploy code below is needed to restart the application automatically because it wouldn't start properly the first time due to the db not fully created
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s



  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

# when coonecting your database to your grafana remeber to use db instead of localhost.
