version: '3.11.6'

services:

  

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    expose:
      - "3306"

  