name: File Check and Run
on: push

jobs:
  check-and-run:
    runs-on: ubuntu-latest
    steps:

#below is for keypair value
    - name: set up ssh
      uses: webfactory/ssh-agent@v0.4.1
      with:
       ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: configure aws cred
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.access_key }}
        aws-secret-access-key: ${{ secrets.secret_access }}
        aws-region: us-east-1
            
    - name: Check for file
      run: |
        if [ -f "main.tf" ]; then
          echo "File found"
        else
          echo "File not found"
          exit 1
        fi
   
    - name: Run the file
      run: | 
        terraform init
        terraform validate
        terraform apply -auto-approve
        sleep 10
        ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -v -i ansible_inventory.yaml playbook.yml

    - name: Delay for 30 seconds
      run: sleep 300s
      
    - name: Destroy Terraform Resources
      run: terraform destroy -auto-approve

